# Generated by Django 4.1.3 on 2022-11-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticleDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=512)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
    ]
