# Generated by Django 4.1.3 on 2022-11-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particle_devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particledevice',
            name='device_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
