# Generated by Django 4.1.3 on 2022-11-11 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('particle_devices', '0002_alter_particledevice_device_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='particledevice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='particledevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='particledevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
