# Generated by Django 4.1.3 on 2022-11-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particle_devices', '0003_alter_particledevice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='particledevice',
            name='device_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
