# Generated by Django 4.1.3 on 2022-11-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particle_devices', '0004_particledevice_device_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particledevice',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
