# Generated by Django 4.1.3 on 2022-11-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particle_devices', '0005_alter_particledevice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='particledevice',
            name='device_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
