# Generated by Django 4.1.3 on 2022-11-19 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('particle_devices', '0006_particledevice_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticleDeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('persist_value', models.BooleanField(default=False)),
                ('event_type', models.IntegerField(choices=[(0, 'Float'), (1, 'Integer'), (2, 'String')], default=2)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_events', to='particle_devices.particledevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
