# Generated by Django 4.1.3 on 2022-11-21 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('particle_devices', '0008_rename_persist_value_particledeviceevent_persist_values_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='particledeviceevent',
            old_name='activitly_monitor',
            new_name='subscribe',
        ),
    ]
