export DATABASE_URL=postgres://postgres:postgres@localhost/dashboarddb
export DEBUG=1
export DJANGO_ALLOWED_HOSTS=localhost\ 127.0.0.1\ \[::1\]\ 0.0.0.0\ 192.168.1.208
export DJANGO_SETTINGS_MODULE=django_project.settings
export POSTGRES_DB=dashboarddb
export POSTGRES_PASSWORD=postgres
export POSTGRES_USER=postgres
export PYTHONUNBUFFERED=1
export SECRET_KEY=foo
