# Generated by Django 4.1.3 on 2022-11-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticleReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at_utc', models.DateTimeField()),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('int_value', models.FloatField(blank=True, null=True)),
                ('str_value', models.CharField(blank=True, max_length=512, null=True)),
                ('event_name', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
