# Generated by Django 4.1.3 on 2022-11-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particle_readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particlereading',
            name='device_id',
            field=models.CharField(max_length=64),
        ),
    ]
