# Generated by Django 4.1.3 on 2022-11-11 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('particle_devices', '0001_initial'),
        ('accounts', '0001_intial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersParticleDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see_functions', models.BooleanField(default=False)),
                ('can_call_functions', models.BooleanField(default=False)),
                ('can_view_events', models.BooleanField(default=False)),
                ('can_send_events', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='particle_devices.particledevice')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
