# Generated by Django 4.1.3 on 2022-11-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particle_devices', '0001_initial'),
        ('accounts', '0002_usersparticledevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='particle_devices',
            field=models.ManyToManyField(blank=True, through='accounts.UsersParticleDevice', to='particle_devices.particledevice'),
        ),
    ]
