# Generated by Django 4.1.3 on 2022-11-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_particle_devices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersparticledevice',
            old_name='can_see_functions',
            new_name='can_view_functions',
        ),
        migrations.AddField(
            model_name='usersparticledevice',
            name='can_view_variables',
            field=models.BooleanField(default=False),
        ),
    ]
