# Generated by Django 4.1.4 on 2022-12-19 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingletonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherManager',
            fields=[
                ('singletonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weather_manager.singletonmodel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(blank=True, max_length=128, null=True)),
                ('polling_enabled', models.BooleanField(default=False)),
                ('polling_seconds', models.IntegerField(default=300)),
            ],
            bases=('weather_manager.singletonmodel',),
        ),
    ]
