# Generated by Django 4.1.4 on 2022-12-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathermanager',
            name='api_url',
            field=models.CharField(default='https://api.openweathermap.org/data/2.5/weather?lat=42.203010&lon=-88.119750&exclude=alerts,daily,hourly,minutely&units=imperial&appid=', max_length=512),
        ),
    ]
