# Generated by Django 4.1.3 on 2022-11-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('wind', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
