# Generated by Django 4.1.4 on 2022-12-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_readings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherReadings',
            new_name='WeatherReading',
        ),
    ]
